name: Scan Container Images

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan Container Image
        uses: crowdstrike/container-image-scan-action@v0.3
        with:
          container_repository: ubuntu
          container_tag: focal-20200115
        env:
          FALCON_CLIENT_ID: "${{ secrets.FALCON_CLIENT_ID }}"
          FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
