name: Scan Container Images

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up chart-testing
        uses: crowdstrike/container-image-scan-action@v0.1
        with:
          falcon_client_id: "<my_falcon_client_id>"
          container_repository: docker.io/library/busybox
        env:
          FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
